<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/1.gif" alt="大眼" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/2.gif" alt="可爱" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/3.gif" alt="大笑" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/4.gif" alt="坏笑" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/5.gif" alt="害羞" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/6.gif" alt="发怒" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/7.gif" alt="折磨" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/8.gif" alt="快哭了" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/9.gif" alt="大哭" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/10.gif" alt="白眼" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/11.gif" alt="晕" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/12.gif" alt="流汗" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/13.gif" alt="困" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/14.gif" alt="腼腆" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/15.gif" alt="惊讶" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/16.gif" alt="憨笑" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/17.gif" alt="色" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/18.gif" alt="得意" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/19.gif" alt="骷髅" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/20.gif" alt="囧" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/21.gif" alt="睡觉" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/22.gif" alt="眨眼" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/23.gif" alt="亲亲" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/24.gif" alt="疑问" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/25.gif" alt="闭嘴" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/26.gif" alt="难过" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/27.gif" alt="淡定" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/28.gif" alt="抗议" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/29.gif" alt="鄙视" /></a>
<a href="javascript:;"><img width="20" height="20" src="<?php bloginfo('template_directory'); ?>/img/smilies/30.gif" alt="猪头" /></a>